In [22]:
# Biblioteca para manipulação de tabelas
import pandas as pd

In [23]:
# Criando um Data Frame
df = pd.read_csv('./DATA_SAMPLE_ORANGE.csv')

## Análise Exploratória

In [24]:
# Visualização dos primeiros registros
df.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2008-01-12 00:00:00,2026-04-24 09:44:00,1.502,0.074,240.17,6.4,0,0,18
1,2006-12-17 00:00:00,2026-04-24 23:39:00,0.374,0.264,245.50,1.8,0,2,0
2,2009-03-06 00:00:00,2026-04-24 17:01:00,0.620,0.300,239.85,3.0,0,1,1
3,2007-09-05 00:00:00,2026-04-24 05:53:00,0.280,0.200,235.72,1.4,0,0,0
4,2008-12-14 00:00:00,2026-04-24 02:57:00,1.372,0.054,243.95,5.6,0,0,18

In [25]:
# Dimensões do data frame
shape = df.shape
print(f'A tabela possui {shape[0]} registros (linhas) e {shape[1]} atributos (colunas)')

A tabela possui 102464 registros (linhas) e 9 atributos (colunas)

In [26]:
# Informações básicas sobre os registros
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102464 entries, 0 to 102463
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Date                   102464 non-null  object
 1   Time                   102464 non-null  object
 2   Global_active_power    102464 non-null  float64
 3   Global_reactive_power  102464 non-null  float64
 4   Voltage                102464 non-null  float64
 5   Global_intensity       102464 non-null  float64
 6   Sub_metering_1         102464 non-null  int64
 7   Sub_metering_2         102464 non-null  int64
 8   Sub_metering_3         102464 non-null  int64
dtypes: float64(4), int64(3), object(2)
memory usage: 7.0+ MB

In [27]:
df.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='object')

In [28]:
# Estatísticas descritivas (colunas numéricas)
# Média, mediana, desvio padrão, min, máx
df.describe()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
count,102464.000000,102464.000000,102464.000000,102464.000000,102464.000000,102464.00000,102464.000000
mean,1.093568,0.124120,240.831564,4.635390,1.140976,1.29019,6.504655
std,1.061280,0.112307,3.241235,4.459188,6.226089,5.80087,8.461418
min,0.076000,0.000000,224.920000,0.200000,0.000000,0.00000,0.000000
25%,0.308000,0.048000,238.990000,1.400000,0.000000,0.00000,0.000000
50%,0.602000,0.100000,241.010000,2.600000,0.000000,0.00000,1.000000
75%,1.528000,0.196000,242.880000,6.400000,0.000000,1.00000,17.000000
max,10.290000,1.078000,253.750000,44.600000,80.000000,77.00000,31.000000

In [29]:
# Separação de colunas
df['Voltage']

0         240.17
1         245.50
2         239.85
3         235.72
4         243.95
           ...
102459    246.67
102460    242.90
102461    238.47
102462    240.21
102463    243.38
Name: Voltage, Length: 102464, dtype: float64

In [30]:
# Média, mediana e desvio padrão ==> Populacionais
df['Voltage'].mean()

np.float64(240.8315637687383)

In [31]:
df['Voltage'].median()

241.01

In [32]:
df['Voltage'].std()

3.241235285091771

In [33]:
# Média, mediana e desvio padrão ==> Amostra
df['Voltage'].sample(frac=0.05).mean()

np.float64(240.87210618778062)

In [34]:
df['Voltage'].sample(frac=0.05).median()

240.99

In [35]:
df['Voltage'].sample(frac=0.05).std()

3.241710758886205